import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import 'tailwindcss/tailwind.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section class="max-w-sm sm:max-w-md md:max-w-lg lg:max-w-xl xl:max-w-2xl p-6 mx-auto bg-white rounded-md shadow-md dark:bg-gray-800">
        <div class=" flex justify-left ">
          <h2 class="text-xl font-bold text-gray-700 capitalize dark:text-white">
            Login
          </h2>
        </div>
        <form>
          <div class="grid grid-cols-1 gap-6 mt-4">
            <div>
              <label
                class="text-gray-700 dark:text-gray-200"
                for="emailAddress"
              >
                Email
              </label>
              <input
                id="emailAddress"
                type="email"
                class="block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-200 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-400 focus:ring-blue-300 focus:ring-opacity-40 dark:focus:border-blue-300 focus:outline-none focus:ring"
              ></input>
            </div>

            <div>
              <div class="form-group">
                <label
                  class="flex justify-left inline-block align-baseline text-gray-700 dark:text-gray-200"
                  for="password"
                >
                  Password
                </label>

                <a
                  href="#"
                  class="flex justify-end inline-block align-baseline font-medium text-sky-500 hover:text-indigo-500"
                >
                  {' '}
                  Forgot your password?{' '}
                </a>
              </div>
              <input
                id="password"
                type="password"
                class="block w-full px-4 py-2 mt-2 text-gray-700 bg-white border border-gray-200 rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-400 focus:ring-blue-300 focus:ring-opacity-40 dark:focus:border-blue-300 focus:outline-none focus:ring"
              ></input>
            </div>
          </div>

          <div class="flex justify-center mt-6">
            <button class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
              Submit
            </button>
          </div>

          <p class=" border-t pt-2 text-sm my-3">
            <div class="flex justify-center">
              <span class="text-gray-700 dark:text-gray-200 pr-1.5">
                Don't have an account ?
              </span>
              <a href="#" class=" text-sky-500">
                Sign up
              </a>
            </div>
          </p>
        </form>
        {/* In case of incorrect username password pair
        <div class="w-full text-white bg-red-500">
          <div class="container flex items-center justify-between px-6 py-4 mx-auto">
            <div class="flex">
              <svg viewBox="0 0 40 40" class="w-6 h-6 fill-current">
                <path d="M20 3.36667C10.8167 3.36667 3.3667 10.8167 3.3667 20C3.3667 29.1833 10.8167 36.6333 20 36.6333C29.1834 36.6333 36.6334 29.1833 36.6334 20C36.6334 10.8167 29.1834 3.36667 20 3.36667ZM19.1334 33.3333V22.9H13.3334L21.6667 6.66667V17.1H27.25L19.1334 33.3333Z"></path>
              </svg>

              <p class="mx-3">Validation Error.</p>
            </div>

            <button class="p-1 transition-colors duration-200 transform rounded-md hover:bg-opacity-25 hover:bg-gray-600 focus:outline-none">
              <svg
                class="w-5 h-5"
                viewBox="0 0 24 24"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M6 18L18 6M6 6L18 18"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
            </button>
          </div>
        </div> */}
      </section>
    </div>
  );
}
